remote_theme: pages-themes/leap-day@v0.2.0

title: Dyallo homepage
description: Bookmark this to keep an eye on my project updates!

# Author info
author: Dennis Dyall
github_username: dennisdyallo
linkedin_username: dennis-dyall

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
timezone: Europe/Stockholm

show_excerpts: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme